name: Release

on:
  push:
    branches: 
      - main
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm clean-install
      - run: npm audit signatures
  release-please:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
  dockerize:
    name: Build and push Docker image to Docker Hub
    environment: default
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/rgummich/bullmq-exporter
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
